# Generated by Django 3.0.5 on 2020-06-26 10:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200626_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
