# Generated by Django 3.0.8 on 2020-08-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20200829_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='email',
            field=models.ManyToManyField(to='newsletter.NewsletterUser'),
        ),
    ]
