# Generated by Django 3.0.8 on 2020-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20200902_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
