# Generated by Django 3.0.5 on 2020-07-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200702_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Closed', 'Closed')], default='New', max_length=10),
        ),
    ]
