# Generated by Django 3.0.8 on 2020-09-10 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_language_settinglang'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='lang',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
