# Generated by Django 3.0.8 on 2020-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200910_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Closed', 'Closed')], default='True', max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=50),
        ),
    ]
