# Generated by Django 3.0.5 on 2020-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopcart',
            old_name='quantité',
            new_name='quantity',
        ),
    ]
