# Generated by Django 3.0.5 on 2020-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduit',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduit',
            name='price',
            field=models.IntegerField(),
        ),
    ]
